services:
  nginx:
    build: ./nginx
    env_file:
      - ./.env
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - web
    networks:
      - main
  web:
    build: .
    image: python:3-alpine
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             sleep 5 &&
             python manage.py migrate &&
             gunicorn inventory.wsgi -b 0.0.0.0:8000"
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - postgres
    volumes:
      - static:/app/static
    networks:
      - main
    restart: on-failure
  postgres:
    image: postgres:14-alpine
    #    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - main
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  main:

volumes:
  pgdata:
  static:
