services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             sleep 5 &&
             python manage.py migrate &&
             gunicorn inventory.wsgi -b 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - main
    restart: on-failure
  postgres:
    image: postgres:14-alpine
    #    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - main
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  main:

volumes:
  pgdata:
