# Generated by Django 2.1.2 on 2018-11-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('when', models.DateTimeField(auto_now_add=True)),
                ('partno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
