# Generated by Django 2.1.2 on 2018-11-05 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181105_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='when',
            new_name='created',
        ),
        migrations.AddField(
            model_name='part',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
