# Generated by Django 2.1.2 on 2018-11-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20181105_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('-updated',)},
        ),
        migrations.RenameField(
            model_name='part',
            old_name='count',
            new_name='total',
        ),
    ]
