# Generated by Django 2.1.2 on 2018-11-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20181105_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='created',
        ),
    ]
