# Generated by Django 2.1.2 on 2018-11-05 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_part_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RenameField(
            model_name='part',
            old_name='updated',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
