# Generated by Django 2.1.2 on 2018-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('partno', models.CharField(max_length=100, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('shelf', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('extra_info', models.CharField(blank=True, max_length=500)),
                ('primary_order_address', models.EmailField(blank=True, max_length=100)),
                ('secondary_order_address', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
