# Generated by Django 2.1.2 on 2018-11-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181112_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('partno',)},
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='primary_order_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='secondary_order_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='shelf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
