# Generated by Django 2.1.2 on 2018-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181115_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='extra_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
