# Generated by Django 2.1.2 on 2018-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181115_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
