# Generated by Django 2.1.2 on 2018-11-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181121_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
