# Generated by Django 2.1.2 on 2018-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20181126_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='part',
            name='alarm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
