# Generated by Django 2.1.2 on 2018-12-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181203_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='alarm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
