# Generated by Django 2.1.7 on 2019-11-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_part_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='created_by',
            new_name='owner',
        ),
    ]
